# Generated by Django 5.1.7 on 2025-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('course', models.ManyToManyField(to='relationship.course')),
            ],
        ),
    ]
